name: torreyt
favicon: null
layout_spectrum: 0.11896
typography_spectrum: 0.75725
title: Torrey Tayenaka
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#010101'
    - '#ea262e'
    - '#ff0000'
    - '#e31c1c'
    - '#bf0000'
  brandStrength: 0.6875
  lightness: 0.75
  saturation: 0.5625
  rhythmicContrast: 0.5
purpose: []
